/* Generated from inventory.csv. Keep the lecture/topic source of truth in inventory.csv. */
window.P400_INVENTORY = {
  "01.02": ["Variables", "Conditional Statements", "Iteration", "Functions", "Coding for Reuse", "A Logging Function"],
  "02.01": ["Pointer Motivation and Memory Addresses", "Pointers and the Address Operator", "Arrays and Pointers", "Pointer Arithmetic", "Initializing Pointers", "Comparing Pointers", "Reference Variables"],
  "02.02": ["Pointer Variables in Memory", "Comparing Pointers", "Pointers to Constants and Constant Pointers", "Pointers as Function Parameters", "Returning and Reassigning Pointers", "Function Pointers"],
  "03.01": ["C++ Memory Model and Pointer Review", "Dynamic Memory Allocation", "Pseudo-Dynamic Arrays", "Real Dynamic Arrays"],
  "04.01": ["OOP Motivation and Progression", "Structures", "Classes Objects and Encapsulation", "Abstract Data Types", "Methods and Public Interfaces"],
  "04.02": ["Methods", "Constructors and Constructor Overloading", "Destructors"],
  "05.01": ["Class Initialization and Relationships", "Dependency Relationships", "Arrays of Objects", "Assertions"],
  "05.02": ["Selecting Members of Objects", "Arrays of Objects on the Stack and Heap", "Resource Acquisition Is Initialization", "Passing Objects to Functions"],
  "06.01": ["Anonymous Classes and Objects", "Adapter Pattern"],
  "06.02": ["C-Strings and Character Arrays", "C-String Library Functions", "String and Numeric Conversions", "Writing C-String Handling Functions"],
  "07.01": ["Constructors and Constructor Overloading", "The this Pointer and Constant Member Functions", "Static Members", "Operator Overloading Preview"],
  "07.02": ["Operator Overloading", "Friend Functions and Stream Operators"],
  "08.01": ["Copy Constructors and Memberwise Assignment", "Shallow Copies and the Serialization Problem"],
  "08.02": ["Deep Copy", "Rvalue References and Move Operations"],
  "09.01": ["Functors", "Range-Based Loops and std::for_each", "Lambda Expressions", "Lambda Use Cases Closures and Callbacks"],
  "09.02": ["Function Templates", "Class Templates"],
  "10.01": ["Type Conversion Operators", "Conversion Constructors", "Operator Chaining", "Lambda and Functor Review"],
  "10.02": ["Conversion Constructors", "First-Class Objects", "Object Conversions", "Conversion Safety"],
  "11.01": ["Class Relationships", "Aggregation and Composition", "Conversion Review"],
  "11.02": ["Class Relationships", "Aggregation and Composition", "Inheritance", "Multiple Inheritance", "Inheritance Access Control", "Virtual Inheritance"],
  "12.01": ["Inheritance and Overriding", "Base Class Construction", "Multiple Inheritance", "Access Specifiers", "Inheritance Design"],
  "12.02": ["Polymorphic Data Structures", "Overriding Functions", "Inheritance and Data Structures", "Inheritance Applications"],
  "13.01": ["Inheritance and Arrays", "Arrays of Class Objects", "Inheritance Design", "Aggregation Review"],
  "13.02": ["Polymorphism", "Virtual Member Functions", "Type Compatibility", "Polymorphic Data Structures", "Polymorphism Design"],
  "14.01": ["Abstract Base Classes", "Polymorphic Arrays", "Object Slicing", "Inheritance Versus Composition", "Dynamic Casting"],
  "14.02": ["Exception Handling", "Exception Safety", "Abstract Classes and Exceptions", "Exception Hierarchies"],
  "15.01": ["Standard Template Library Preview", "Vectors of Vectors", "Design Exercise"],
  "15.02": ["Function Templates", "Template Arguments", "Template Specialization", "Generic Program Maintenance"],
  "16.01": ["Fill In the Missing Code", "Object-Oriented Programming", "Defining Member Functions", "Creating and Using Objects", "Introduction to Classes", "Abstract Data Types - Part 2"],
  "16.02": ["Destructor", "Constructor Overloading", "Parameterized Constructor", "Default Constructor", "What is a Constructor"],
  "17.01": ["Vectors of Objects", "Arrays of Objects"]
};

window.P400_LECTURE_TITLES = {
  "01.01": "Course Introduction",
  "01.02": "C++ Programming Review",
  "02.01": "Intro to Pointers",
  "02.02": "Working with Pointers",
  "03.01": "Dynamic Memory",
  "03.02": "Programming Exercise III",
  "04.01": "OOP I",
  "04.02": "Methods and Constructors",
  "05.01": "Class Relationships and Object Arrays",
  "05.02": "Passing Objects",
  "06.01": "Anonymous Objects and Adapter Pattern",
  "06.02": "C-Strings and Conversions",
  "07.01": "More OOP: Constructors and Static Members",
  "07.02": "Operator Overloading and Friends",
  "08.01": "Shallow Copies",
  "08.02": "Deep Copies and Move Operations",
  "09.01": "Functors and Lambda Expressions",
  "10.01": "Type Conversion and Operator Chaining",
  "10.02": "Converting Constructors and Object Conversions",
  "11.01": "Class Relationships, Aggregation, and Composition",
  "11.02": "Inheritance and Multiple Inheritance",
  "12.01": "Inheritance Construction and Overriding",
  "12.02": "Polymorphic Data Structures and Inheritance Applications",
  "13.01": "Inheritance and Arrays",
  "13.02": "Polymorphism and Virtual Member Functions",
  "14.01": "Abstract Base Classes and Polymorphic Arrays",
  "14.02": "Exception Handling and Exception Hierarchies",
  "15.01": "STL Preview and Vectors of Vectors",
  "15.02": "Function Templates and Generic Programming",
  "16.01": "Classes and Member Functions",
  "16.02": "Constructors and Destructors",
  "17.01": "Arrays and Vectors of Objects"
};
